name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches-ignore:
      - 'feature/*' # Ignore build feature branch on push; feature branches will be build only for pull requests.
      - 'Feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@1.0.0

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: dotnet msbuild -m -v:n -p:Configuration=Release src/GitMirror.sln
