name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pull-request-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@1.0.0

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: dotnet pack --configuration release src/GitMirror.sln -p:Version=1.0.0 --version-suffix "build.${{ github.run_number }}"
